Feature/project setup
Fancy-Colors/FCG-Fancy-Colors-Game pull request #1
Opened 2023-02-22 20:32 UTC by DNLHC

2023-02-23 05:03 UTC, alex-kurkov approved these changes
по мне все ок - все установилось и работает, yarn только в package.json расставил все по алфавиту...

2023-02-23 06:38 UTC, Aleksa-esme reviewed
все ок

2023-02-23 07:44 UTC, mozg3000 commented on package.json
> +    "node": ">=16"
версия указанная тут не соответствует жесткой версии указанной в .nvmrc v16.19.0.
Зачем тут указывать версию которая не соответствует действительности, даже если эта настройка не применяется? Это может в заблуждение ввести мне кажется и предлагаю удалить этот пункт вообще.

2023-02-23 07:44 UTC, mozg3000 commented on .nvmrc
> +v16.19.0
мы договаривались использовать версию ноды 18.x.x.

2023-02-23 07:56 UTC, Aleksa-esme approved these changes
все ок

2023-02-23 08:28 UTC, EzhikTT commented on package.json
> +    "node": ">=16"
Минорная версия и патч не важны ждя этого пункта

2023-02-23 08:30 UTC, DNLHC commented on .nvmrc
> +v16.19.0
Договорились использовать 16, т.к большинство облачных серверов еще не поддерживают 18 (Netlify, Cloudflare), а нам еще в будущем деплоить на yandex-cloud.

2023-02-23 08:31 UTC, EzhikTT requested changes
Лок файл не обязателен в репозитории, тк он генерируемый

2023-02-23 08:31 UTC, EzhikTT commented on packages/client/src/styles/index.pcss
> +h5 h6 {
Тут не должно быть запятой?

2023-02-23 08:31 UTC, EzhikTT commented on packages/client/src/app.test.tsx
> +import App from './app';
А почему поменяли регистр имени?

2023-02-23 08:31 UTC, EzhikTT commented on .nvmrc
> +v16.19.0
Да, берите TLS или current

2023-02-23 08:33 UTC, DNLHC commented on packages/client/src/app.test.tsx
> +import App from './app';
Договорились использовать kebab-case в именовании файлов проекта.

2023-02-23 08:48 UTC, DNLHC commented
> Лок файл не обязателен в репозитории, тк он генерируемый

Локфайл нужен для фиксации версий зависимостей и должен быть в репозитории
https://yarnpkg.com/getting-started/qa/#should-lockfiles-be-committed-to-the-repository

2023-02-23 08:53 UTC, mozg3000 approved these changes
Круто, много кастомных настроек в конфигах.

2023-02-23 09:32 UTC, DNLHC commented on .nvmrc
> +v16.19.0
Зафиксировал LTS

2023-02-26 08:33 UTC, EzhikTT approved these changes
Все ок

2023-02-26 10:09 UTC, merged