Создала компонент Button
Fancy-Colors/FCG-Fancy-Colors-Game pull request #10
Opened 2023-02-25 10:38 UTC by Aleksa-esme

![2023-02-23_17-04-56](https://user-images.githubusercontent.com/58600329/221352296-1dd4fcd2-b1c9-4fc1-90c0-7f5687958b98.png)

2023-02-25 11:39 UTC, mozg3000 approved these changes

2023-02-25 11:39 UTC, mozg3000 commented on packages/client/src/components/button/button.tsx
> +export const Button = ({
Вот тут тип не нужно указать?

`Button: FC<ButtonProps>`

2023-02-25 11:39 UTC, mozg3000 commented on packages/client/src/components/button/button.module.pcss
> +  filter: brightness(90%);
Вы хотели вроде сделать общий ховер для всех. Не нужно ли тогда 90% вынести в переменные?
`:root {
  --hover-brightness: 90%;
}
`

2023-02-25 11:39 UTC, mozg3000 commented on packages/client/src/components/button/button.tsx
> +  type?: 'button' | 'submit';
Я бы сюда же добавил 'link' вместо isLink?: boolean.
всё равно они вместе никогда не могут быть. тогда бы type был бы required пропсом или по умолчанию тип link можно было бы ставить.
`jsx

      { type === 'link'? (
        <a href={link} className={cnButton}>
          <span className={styles.btn}>{title}</span>
        </a>
      ) : (
        <button type={type} className={cnButton} onClick={onClick}>
          <span className={styles.btn}>{title}</span>
        </button>
      )}
`

2023-02-25 11:39 UTC, mozg3000 commented on packages/client/src/components/button/button.tsx
> +  size?: 's' | 'm' | 'l';
Не следует ли размеры тоже сделать (глобальным) enum раз вы их используете везде и харкодите строчки?

2023-02-25 12:02 UTC, alex-kurkov reviewed
Саша, небольшие поправочки можно внести, а в целом - ок!

2023-02-25 12:02 UTC, alex-kurkov commented on packages/client/src/components/button/button.tsx
> +  type?: 'button' | 'submit';
можно проще - через двойное отрицание `!!link`

2023-02-25 12:27 UTC, DNLHC reviewed
1. Когда делают обёртки над нативными элементами, необходимо делать компонент максимально гибким, чтобы он мог работать как нативный элемент.
К примеру в данной реализации атрибуты `disabled`, `name` или `form` не повесить. И другие обработчики событий кроме `onClick` не повесить.

2. Текстовый контент кнопки лучше передавать через `children`, а не через пропс, чтобы была возможность передавать произвольный контент, например текст с иконкой (плюс к гибкости)
```tsx
<Button>Регистрация</Button>
```

Как можно сделать кнопку гибкой:
```diff
diff --git a/packages/client/src/components/button/button.tsx b/packages/client/src/components/button/button.tsx
index a1e6e59..2dfd6e0 100644
--- a/packages/client/src/components/button/button.tsx
+++ b/packages/client/src/components/button/button.tsx
@@ -14,25 +14,22 @@ const ButtonColorChoice = {
 };
 
 type ButtonProps = {
-  type?: 'button' | 'submit';
   link?: string;
-  title: string;
   color?: keyof typeof ButtonColor;
   size?: 's' | 'm' | 'l';
   className?: string;
   isLink?: boolean;
-  onClick?: () => void;
-};
+  children: React.ReactNode;
+} & JSX.IntrinsicElements['button'];
 
 export const Button = ({
-  type = 'submit',
   link,
-  title = '',
   color = ButtonColor.colored,
+  children,
   size = 'm',
   className,
   isLink = false,
-  onClick,
+  ...props
 }: ButtonProps) => {
   const cnButton = cn(
     className,
@@ -45,11 +42,11 @@ export const Button = ({
     <>
       {isLink ? (
         <a href={link} className={cnButton}>
-          <span className={styles.btn}>{title}</span>
+          <span className={styles.btn}>{children}</span>
         </a>
       ) : (
-        <button type={type} className={cnButton} onClick={onClick}>
-          <span className={styles.btn}>{title}</span>
+        <button className={cnButton} {...props}>
+          <span className={styles.btn}>{children}</span>
         </button>
       )}
     </>
```
Таким образом компонент может работать как нативный элемент.
```tsx
<Button onClick={onClick} id="button-id" disabled={disabled} type="button">
  My Button
</Button>
```
А в самом компоненте больше не нужно заморачиваться насчет поддержки всех возможных атрибутов и событий нативного элемента.

2023-02-25 12:44 UTC, DNLHC commented on packages/client/src/components/button/button.tsx
> +        <a href={link} className={cnButton}>
нам скорей всего не понадобится `<a>` элемент как кнопка, у нас вроде нет ссылок-кнопок на сторонние сайты в проекте, а вот `Link` из `react-router` будет нужен для внутренней навигации.
Для простоты реализации можно сделать два компонента: `Button` и `ButtonLink` (экспортируются из одного файла) классы и стилизацию можно переиспользовать.

2023-02-26 08:10 UTC, Aleksa-esme commented on packages/client/src/components/button/button.tsx
> +  size?: 's' | 'm' | 'l';
они разные везде для разных компонентов

2023-02-26 08:26 UTC, Aleksa-esme commented on packages/client/src/components/button/button.tsx
> +      {isLink ? (
можно просто link, без двойного отрицания - у нас в eslint включено правило:
Redundant double negation.eslint[no-extra-boolean-cast]
{  link ? () : () }

2023-02-26 08:37 UTC, EzhikTT commented on packages/client/src/components/button/button.tsx
> +  type?: 'button' | 'submit';
А заем двойное отрицание? Современный js и ts могут сами типы приводить

2023-02-26 08:38 UTC, EzhikTT commented on packages/client/src/components/button/button.tsx
> +  type?: 'button' | 'submit';
+ можно не ставить круглые скобки, если начинать писать компонент на уровне с ? или :

2023-02-26 08:39 UTC, EzhikTT requested changes
Порешайте с `link` и `isLink`, и все ок

2023-02-26 08:45 UTC, Aleksa-esme commented on packages/client/src/components/button/button.tsx
> +        <a href={link} className={cnButton}>
ты имеешь ввиду сделать ButtonLink как:

import { Link } from 'react-router-dom';

<Link to={link} className={cnButton}>
  <span className={styles.btn}>{children}</span>
</Link>
?
Изначально не хотела добавлять <a> - не правильно вас из переписки в чате значит поняла

2023-02-26 09:18 UTC, DNLHC commented on packages/client/src/components/button/button.tsx
> +        <a href={link} className={cnButton}>
Да, всё верно, сделать обёртку над `Link`
И импортировать кнопки вот так:
```tsx
import { Button, ButtonLink } from 'components/button'
```

2023-02-26 09:32 UTC, Aleksa-esme commented on packages/client/src/components/button/button.tsx
> +  type?: 'button' | 'submit';
у нас скобки какой то из линтеров автоматом ставит

2023-02-26 09:49 UTC, mozg3000 approved these changes

2023-02-26 09:49 UTC, mozg3000 commented on packages/client/src/components/button/button.tsx
> +  size?: 's' | 'm' | 'l';
Я говорил не по цифры, про 's' | 'm' | 'l' они в той или иной комбинации повторяются.

2023-02-26 09:49 UTC, mozg3000 commented on packages/client/src/components/button/button.tsx
> +  ...props
Откуда тут берется ...props , если сам этот объект извлекает значения из него?

2023-02-26 11:15 UTC, alex-kurkov approved these changes

2023-02-26 14:36 UTC, mozg3000 approved these changes

2023-02-28 09:59 UTC, EzhikTT commented on packages/client/src/components/button/button.tsx
> +  ...props
Это для тех, которые могут быть допником из не деструктурированных

2023-02-28 09:59 UTC, EzhikTT approved these changes
Все ок

2023-02-28 11:36 UTC, Marmeloy approved these changes

2023-02-28 13:40 UTC, DNLHC approved these changes

2023-02-28 14:27 UTC, merged