Добавил компонент ProfileLink
Fancy-Colors/FCG-Fancy-Colors-Game pull request #11
Opened 2023-02-25 14:15 UTC by Marmeloy

### Какую задачу решаем

Компонент отображения профиля пользователя в сайдбаре. 
<img width="412" alt="изображение" src="https://user-images.githubusercontent.com/20978914/221361400-97b011e7-cb11-4630-bbd3-a6340eaf9f33.png">

Для реализации свёрнутого сайдбара добавил возможность изменить размер компонента, чтобы отображалась только кнопка с шестерёнкой:

<img width="73" alt="изображение" src="https://user-images.githubusercontent.com/20978914/221361506-678a825c-0993-4a67-9abe-3547b793e163.png">

### Пример использования:
```
<ProfileLink
      email="andrew.studenov@ya.ru"
      name="Андрей Студёнов"
      avatar="https://avatars.githubusercontent.com/u/20978914?v=4"
      size="l"
/>
```

Через аттрибут onClick можно передать функцию, которая будет вызываться при нажатии на кнопку с шестерёнкой.

2023-02-25 14:20 UTC, mozg3000 reviewed
Притяни обновления из ui-kit к себе в ветку чтобы она соответствовала текущему состоянию ui-kit.

2023-02-25 16:09 UTC, DNLHC requested changes

2023-02-25 16:09 UTC, DNLHC commented on packages/client/src/components/profile-link/profile-link.tsx
> +        )}
и здесь
```suggestion
        {size === 'l' && (
          <div className={styles.info}>
            <div className={styles.avatar}>
              <Avatar size="xs" name={name} avatar={avatar} />
            </div>
            <div className={cn(styles.content, 'text-main')}>
              <div className={styles.name}>{name}</div>
              <div className={styles.email}>{email}</div>
            </div>
          </div>
        )}
```

2023-02-25 16:09 UTC, DNLHC commented on packages/client/src/components/profile-link/profile-link.tsx
> +        <button className={styles.settings} onClick={onClick}>
у кнопок по умолчанию `type` стоит `submit`, неплохо бы указать, что кнопка не сабмитит форму
`type="button"`

2023-02-25 16:09 UTC, DNLHC commented on packages/client/src/components/profile-link/profile-link.tsx
> +const IconColor = '#6644EC';
почему константа в PascalCase?
В таком регистре принято называть классы и типы

2023-02-25 16:09 UTC, DNLHC commented on packages/client/src/components/profile-link/profile-link.module.pcss
> +}
В проекте есть [postcss-nested](https://github.com/postcss/postcss-nested)
```suggestion
.profileLink {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-right: 14px;
  
  &.small {
    padding-right: 0;
  }
}
```

2023-02-25 16:35 UTC, alex-kurkov reviewed
Андрей, нужно внести правки, озвученные Данилой. И призывай нас еще раз.

2023-02-25 17:09 UTC, DNLHC approved these changes

2023-02-26 05:20 UTC, alex-kurkov approved these changes

2023-02-26 08:41 UTC, EzhikTT requested changes

2023-02-26 08:41 UTC, EzhikTT commented on packages/client/src/components/icon/icon.tsx
> +  size: 'xs' | 'small' | 'medium' | 'large';
В предыдущем [ПРе](https://github.com/Fancy-Colors/FCG-Fancy-Colors-Game/pull/10) другой формат. Согласуйте плиз

2023-02-26 10:51 UTC, Aleksa-esme approved these changes

2023-02-28 10:01 UTC, EzhikTT approved these changes
Все ок

2023-02-28 13:16 UTC, alex-kurkov requested changes
Андрей, нужно 
1. центрировать иконку в узр=ком вью
2. добавить пропс active, рендерящий фон

2023-02-28 16:06 UTC, alex-kurkov approved these changes

2023-03-01 11:31 UTC, merged