Добавляет Footer
Fancy-Colors/FCG-Fancy-Colors-Game pull request #14
Opened 2023-02-26 13:18 UTC by alex-kurkov

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-26 15:01 UTC, DNLHC requested changes

2023-02-26 16:55 UTC, alex-kurkov commented on packages/client/src/components/footer/footer.tsx
> +  icons: IconLink[];
> может лучше будет переименовать `icons` в `links`, т.к это в первую очередь список ссылок, а иконки - это уже декоративная часть этих ссылок.

ОК!

2023-02-26 16:55 UTC, alex-kurkov commented on packages/client/src/components/footer/footer.tsx
> +            <li key={`social-link-${type}`}>
> тут можно оставить просто `key={type}` уникальность ключей нужна только внутри этой коллекции, за пределами она не важна.

ОК!

2023-02-26 16:55 UTC, alex-kurkov commented on packages/client/src/components/footer/footer.tsx
> +              <Link to={link} target="_blank">
> Компонент `Link` нужен для внутренней навигации SPA приложения, для внешних ссылок нужно использовать обычный `<a>`

ОК!

2023-02-26 17:17 UTC, DNLHC requested changes

2023-02-26 17:17 UTC, DNLHC commented on packages/client/src/components/footer/footer.tsx
> +import { Link } from 'react-router-dom';
Импорт `Link` нужно удалить, он больше не используется. В остальном всё хорошо.

2023-02-27 06:11 UTC, alex-kurkov commented on packages/client/src/components/footer/footer.tsx
> +import { Link } from 'react-router-dom';
Done!

2023-02-27 17:21 UTC, DNLHC approved these changes

2023-02-27 18:07 UTC, Aleksa-esme approved these changes

2023-02-28 08:07 UTC, mozg3000 approved these changes

2023-02-28 10:07 UTC, EzhikTT approved these changes
Все ок

2023-02-28 10:21 UTC, merged