add DateFormatted Component and normalizer utility
Fancy-Colors/FCG-Fancy-Colors-Game pull request #2
Opened 2023-02-23 10:37 UTC by alex-kurkov

### Какую задачу решаем
Компонент DateFormatted
принимает необязательный пропс ```date``` в формате ISO строки, возвращает тег <time> с отформатированным текстовым представлением даты:

Без пропса date - указывает на сейчас
> Сегодня 15:29

С пропсом:
> Вчера 06:48
> Позавчера 04:08
> 1 ноября 2022 г. 17:55

не применяет никаких стилей, должен стилизоваться родителем

### Скриншоты/видяшка (если есть)

![Скриншот 23-02-2023 13_33_08](https://user-images.githubusercontent.com/65237410/220882870-8c23941c-8192-450e-a77f-887a1cb603f3.jpg)

### TBD (если есть)

2023-02-23 10:58 UTC, DNLHC requested changes

2023-02-23 10:58 UTC, DNLHC commented on packages/client/src/components/date-formatted/date-formatted.tsx
> +import { normalizeDate } from 'utils/normalizeDate';
Договорились именовать файлы по kebab-case

2023-02-23 10:58 UTC, DNLHC commented on packages/client/src/utils/normalizeDate.ts
> +    now.getTime() - date.getTime() < 1000 * 60 * 60 * 24 * 3 &&
Может стоит вынести условия и магические значения в константы, чтобы улучшить читаемость?

2023-02-23 11:00 UTC, alex-kurkov commented on packages/client/src/components/date-formatted/date-formatted.tsx
> +import { normalizeDate } from 'utils/normalizeDate';
да, мой косяк, исправляю

2023-02-23 11:01 UTC, alex-kurkov commented on packages/client/src/utils/normalizeDate.ts
> +    now.getTime() - date.getTime() < 1000 * 60 * 60 * 24 * 3 &&
ОК!

2023-02-23 11:07 UTC, DNLHC commented on packages/client/src/components/date-formatted/date-formatted.tsx
> +}: Props) => {
Здесь `Props` можно не указывать, он из дженерика `FC<Props>` уже знает тип аргумента

2023-02-23 11:13 UTC, DNLHC approved these changes

2023-02-23 11:30 UTC, mozg3000 approved these changes

2023-02-23 11:39 UTC, DNLHC commented
Взглянув еще раз решил добавить, может стоит экспортировать компоненты через `index.ts`?
Пример структуры компонента
```
date-formatted
├── date-formatted.tsx
├── date-formatted.module.pcss
├── date-formatted.test.tsx
└── index.ts
```
импортировать можно через `components/date-formatted` вместо `components/date-formatted/date-formatted`

2023-02-23 12:14 UTC, Aleksa-esme reviewed
мы коммиты вроде договаривались на русском делать

2023-02-23 12:28 UTC, DNLHC commented
> > Взглянув еще раз решил добавить, может стоит экспортировать компоненты через `index.ts`? Пример структуры компонента
> > ```
> > date-formatted
> > ├── date-formatted.tsx
> > ├── date-formatted.module.pcss
> > ├── date-formatted.test.tsx
> > └── index.ts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > импортировать можно через `components/date-formatted` вместо `components/date-formatted/date-formatted` Как думаешь?
> 
> в яндексовской лекции из ШРИ по реакту разработчик из кинопоиска рассказывал, что когда они убрали все экспорты в приложении через index.ts, то оно стало значительно быстрее работать. Могу поискать эту лекцию

В больших проектах с тысячами модулей возможно и повлияет, в нашем случае не думаю что разница будет

2023-02-23 13:21 UTC, Aleksa-esme approved these changes

2023-02-23 17:33 UTC, DNLHC approved these changes

2023-02-24 14:25 UTC, Marmeloy approved these changes
Всё ок

2023-02-24 15:39 UTC, merged