Добавляет `Lead`
Fancy-Colors/FCG-Fancy-Colors-Game pull request #21
Opened 2023-03-01 12:01 UTC by alex-kurkov

### Какую задачу решаем
Используется либа `swiper`, поэтому не забываем за-yarn-ить новую зависимость

Пропсы
```jsx
type TSlide = {
  imageUrl: string;
  title?: string;
  isH1?: boolean;
  text?: string;
};
type Props = {
  slides: TSlide[];
};
```

### Скриншоты/видяшка (если есть)
![Скриншот 01-03-2023 14_55_52](https://user-images.githubusercontent.com/65237410/222133111-70440dd6-f82b-41ca-83dc-5d790b30e8bb.jpg)
![Скриншот 01-03-2023 14_56_27](https://user-images.githubusercontent.com/65237410/222133123-b9f818f7-8388-43d4-803e-ef108f1918cb.jpg)
![Скриншот 01-03-2023 14_57_31](https://user-images.githubusercontent.com/65237410/222133127-fbce8088-a0bf-4251-88fb-3dabd79e42f3.jpg)

2023-03-01 12:12 UTC, mozg3000 approved these changes

2023-03-01 12:12 UTC, mozg3000 commented on packages/client/src/components/lead/lead.tsx
> +        className={cn(styles.arrow, styles.left)}
А почему ты тут не используешь компонент Button?

2023-03-01 12:12 UTC, mozg3000 commented on packages/client/src/components/lead/lead.tsx
> +      <button
и тут тоже

2023-03-01 13:32 UTC, EzhikTT requested changes

2023-03-01 13:32 UTC, EzhikTT commented on packages/client/src/components/lead/lead.tsx
> +        className={cn(styles.arrow, styles.left)}
Полностью согласен с вопросом

2023-03-01 15:30 UTC, DNLHC commented on packages/client/src/components/lead/lead.module.pcss
> +    color: var(--color-primary-white, #fff);
1. я бы предложил стилизовать по классам, т.к если в разметке тег понадобится изменить придётся править и стили.
2. а зачем здесь вообще напрямую обращаться к элементам, разве они не будут наследовать цвет из родительского элемента? Можно color просто повесить на `.info`

2023-03-01 19:06 UTC, DNLHC approved these changes

2023-03-02 13:08 UTC, Aleksa-esme approved these changes

2023-03-02 13:16 UTC, EzhikTT commented on packages/client/src/components/lead/lead.tsx
> +          {isH1 ? (
Можно написать на строчку с `?:` и не придется ставить круглые скобки

2023-03-02 13:16 UTC, EzhikTT approved these changes
Все ок

2023-03-02 14:49 UTC, merged