Layout/how to modal/100
Fancy-Colors/FCG-Fancy-Colors-Game pull request #23
Opened 2023-03-02 06:14 UTC by alex-kurkov

Зависит от завершения работы над PR компонента [Modal](https://github.com/Fancy-Colors/FCG-Fancy-Colors-Game/pull/20), в который предполагается добавление пропса onClick

![Скриншот 02-03-2023 09_11_16](https://user-images.githubusercontent.com/65237410/222345780-3d483572-3861-47df-baea-0b92299c89e6.jpg)

2023-03-02 13:20 UTC, EzhikTT requested changes

2023-03-02 13:20 UTC, EzhikTT commented on packages/client/src/modals/how-to-modal/how-to-modal.tsx
> +const modalRoot = document.querySelector('#modals') as Element;
Почему здесь селектор, а не человеческий `getElementById`?

2023-03-02 13:20 UTC, EzhikTT commented on packages/client/index.html
> +    <div id="modals"></div>
А почему оно за пределами основного приложения?

2023-03-02 14:34 UTC, alex-kurkov commented on packages/client/index.html
> +    <div id="modals"></div>
Использует [ReactDOM.createPortal](https://ru.react.js.org/docs/portals.html)

2023-03-02 14:35 UTC, alex-kurkov commented on packages/client/index.html
> +    <div id="modals"></div>
Впрочем, убрали порталы из реализации этой модалки

2023-03-02 19:46 UTC, Marmeloy approved these changes

2023-03-03 08:14 UTC, mozg3000 approved these changes

2023-03-03 08:41 UTC, Aleksa-esme approved these changes

2023-03-03 15:17 UTC, DNLHC approved these changes

2023-03-04 08:26 UTC, EzhikTT approved these changes
Все ок

2023-03-04 10:02 UTC, merged