Верстка `MainPage`
Fancy-Colors/FCG-Fancy-Colors-Game pull request #25
Opened 2023-03-02 17:58 UTC by alex-kurkov

### Какую задачу решаем
Верстка MainPage

## Для нормальной интеграции также изменены компоненты-дети:
- для резиновости изменены стили `GameCard`
- добавлена логика закрытия модалки по __ESC__ и клику на оверлей (там, по хорошему надо бы слушателя `KeyboardEvent` на document или window навесить, а не на div, но это потом, но обработку клавиатурного клика требует a11y)
- уточнен переход по роуту `/how-to` в `SideMenu` (передается стейт)

## А также их родители:
- настроены уже существующие роуты `/`, `/how-to`
- добавлены общие стили (фон приложения и контентная часть)

### Скриншоты/видяшка (если есть)
![Скриншот 02-03-2023 20_57_29](https://user-images.githubusercontent.com/65237410/222512409-e9a4b90a-809d-40e2-8cd0-90a735ddbbc7.jpg)![Скриншот 02-03-2023 20_57_08](https://user-images.githubusercontent.com/65237410/222512423-26c8dc95-fc1d-4fc0-b025-0f173a3b5326.jpg)![Скриншот 02-03-2023 20_56_48](https://user-images.githubusercontent.com/65237410/222512427-6dea1245-625b-4500-ba67-a6f9b5e3e292.jpg)

2023-03-02 19:22 UTC, DNLHC requested changes

2023-03-02 19:22 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.tsx
> +        <Link to="profile" onClick={() => setActiveLink('/profile')}>
Лучше не синхронизировать текущий роут через клики `setActiveLink`, переходы происходят не только по кликам, но и по браузерным кнопкам вперёд/назад, такая схема будет работать неправильно.
Для контроля активного роута есть [`NavLink`](https://reactrouter.com/en/main/components/nav-link) внутрь которого можно передать компонент через функцию.
```diff
diff --git a/packages/client/src/components/side-menu/side-menu.tsx b/packages/client/src/components/side-menu/side-menu.tsx
index 3ab3a06..a59630e 100644
--- a/packages/client/src/components/side-menu/side-menu.tsx
+++ b/packages/client/src/components/side-menu/side-menu.tsx
@@ -2,7 +2,7 @@ import { FC, useState } from 'react';
 import styles from './side-menu.module.pcss';
 import cn from 'classnames';
 import { NavigationLink } from 'components/navigation-link';
-import { Link } from 'react-router-dom';
+import { Link, NavLink } from 'react-router-dom';
 import { ProfileLink } from 'components/profile-link';
 import { Footer } from 'components/footer';
 import { ReactComponent as Logo } from 'assets/logo.svg';
@@ -72,7 +72,6 @@ const SOCIAL_LINKS = [
 ];
 
 export const SideMenu: FC = () => {
-  const [activeLink, setActiveLink] = useState(LINKS[0].link);
   const [expanded, setExpanded] = useState(true);
 
   return (
@@ -88,7 +87,7 @@ export const SideMenu: FC = () => {
           ['w-1']: !expanded,
         })}
       >
-        <Link to="/" onClick={() => setActiveLink('/')}>
+        <Link to="/">
           <div className={styles.logo}>
             {expanded ? (
               <Logo width="100%" height="100%" fill={LOGO_COLOR} />
@@ -101,21 +100,23 @@ export const SideMenu: FC = () => {
         <div className={styles.mainLinksWrap}>
           {expanded && <p className={cn(styles.textMenu, 'text-menu')}>Меню</p>}
           {LINKS.map(({ iconType, text, link, informer }) => (
-            <Link key={iconType} to={link} onClick={() => setActiveLink(link)}>
-              <NavigationLink
-                text={text}
-                iconType={iconType}
-                active={link === activeLink}
-                expanded={expanded}
-                informer={informer}
-              />
-            </Link>
+            <NavLink key={iconType} to={link}>
+              {({ isActive }) => (
+                <NavigationLink
+                  text={text}
+                  iconType={iconType}
+                  active={isActive}
+                  expanded={expanded}
+                  informer={informer}
+                />
+              )}
+            </NavLink>
           ))}
         </div>
 
         {expanded && <div className={styles.delimiter} />}
 
-        <Link to="profile" onClick={() => setActiveLink('/profile')}>
+        <Link to="profile">
           <ProfileLink {...PROFILE} expanded={expanded} />
         </Link>
 
@@ -149,7 +150,7 @@ export const SideMenu: FC = () => {
           <NavigationLink
             text={EXIT.text}
             iconType={EXIT.iconType}
-            active={EXIT.link === activeLink}
+            active={false}
             expanded={expanded}
           />
         </button>
```

2023-03-02 19:22 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.tsx
>  type Link = {
В файле заимпортирован компонент `Link`, а тут тип с названием `Link`, может переименовать?

2023-03-02 19:22 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.tsx
> +    link: '/leaderboard',
У нас есть енум `RouterPaths` с путями в `src/app.tsx`, лучше использовать его.

2023-03-02 19:22 UTC, DNLHC commented on packages/client/src/pages/main/main.tsx
> +                      <GameCard {...item} key={item.id} />
Здесь `key` не нужен, достаточно у родительского элемента

2023-03-02 19:22 UTC, DNLHC commented on packages/client/src/components/modal/modal.tsx
> +          role="button"
здесь редкий случай, когда отключение правила линтера оправдано)
`eslint-disable-next-line jsx-a11y/no-static-element-interactions`
 а роль `button` с модалки надо убрать

2023-03-03 08:24 UTC, mozg3000 approved these changes

2023-03-03 11:15 UTC, DNLHC approved these changes

2023-03-04 02:55 UTC, Marmeloy approved these changes

2023-03-04 08:29 UTC, EzhikTT requested changes

2023-03-04 08:29 UTC, EzhikTT commented on packages/client/src/components/side-menu/side-menu.tsx
> +import { RouterPaths } from 'src/app.types';
А почему константы из `src/mock/side-menu-links` в верхнем регистре, а эти константы в `PascalCase`?

2023-03-04 10:04 UTC, merged