Добавила компонент формы регистрации и логина
Fancy-Colors/FCG-Fancy-Colors-Game pull request #29
Opened 2023-03-04 10:34 UTC by Aleksa-esme

![2023-03-04_13-02-12](https://user-images.githubusercontent.com/58600329/222894857-ad86170e-1392-42f5-bb9d-ee557eff44ea.png)
![2023-03-04_13-04-06](https://user-images.githubusercontent.com/58600329/222894861-d20985c2-3137-4e95-a4d1-7993ae55834a.png)
![2023-03-04_13-10-16](https://user-images.githubusercontent.com/58600329/222894864-be740bf7-e87d-4ce3-9af9-785cd3cec94b.png)

2023-03-04 18:28 UTC, DNLHC requested changes

2023-03-04 18:28 UTC, DNLHC commented on packages/client/src/components/form/form.tsx
> +          })}
Подход DRY это хорошо, но не всегда оправдан, иногда это ведёт к переусложнению. Мне кажется проще было сделать два компонента формы (пусть пришлось бы часть копипасть), чем вот так, менее гибко.
Такое сложней поддерживать и использовать плюс частично теряется типизация.
Исправлять необязательно, просто замечание.

2023-03-04 18:28 UTC, DNLHC commented on packages/client/src/mock/register-fields.ts
> +      ) as HTMLInputElement;
К слову о разделении форм на разные компоненты, не пришлось бы делать такие некрасивые вещи)

Еще можно исправить вот так:
```diff
diff --git a/packages/client/src/components/form/form.tsx b/packages/client/src/c
omponents/form/form.tsx
index 68e6d0f..4166a76 100644
--- a/packages/client/src/components/form/form.tsx
+++ b/packages/client/src/components/form/form.tsx
@@ -2,7 +2,7 @@ import { FC } from 'react';
 import { Button, ButtonColor } from 'components/button';
 import { TextField } from 'components/text-field';
 import { Link } from 'react-router-dom';
-import { useForm, SubmitHandler, FieldValues, Validate } from 'react-hook-form';
+import { useForm, SubmitHandler, FieldValues, Validate, UseFormGetValues } from 
'react-hook-form';
 import cn from 'classnames';
 import styles from './form.module.pcss';
 
@@ -10,7 +10,7 @@ type Props = {
   linkTo: string;
   buttonTitle: string;
   linkTitle: string;
-  fields: Array<Field>;
+  fields: (getValues: UseFormGetValues<FieldValues>) => Field[];
   onClick?: () => void;
   onSubmit: SubmitHandler<FieldValues>;
 };
@@ -36,13 +36,14 @@ export const Form: FC<Props> = ({
     register,
     handleSubmit,
     formState: { errors },
+    getValues,
   } = useForm({
     mode: 'onBlur',
   });
 
   return (
     <form className={styles.form} onSubmit={handleSubmit(onSubmit)} {...props}>
-      {fields.map((field) => (
+      {fields(getValues).map((field) => (
         <TextField
           placeholder={field.placeholder}
           type={field.type}
diff --git a/packages/client/src/mock/register-fields.ts b/packages/client/src/mo
ck/register-fields.ts
index 1381273..e6f5b17 100644
--- a/packages/client/src/mock/register-fields.ts
+++ b/packages/client/src/mock/register-fields.ts
@@ -1,3 +1,4 @@
+import { FieldValues, UseFormGetValues } from 'react-hook-form';
 import {
   validateEmail,
   validateLogin,
@@ -6,7 +7,7 @@ import {
   validatePhone,
 } from '../utils/validation';
 
-export const REGISTER_FIELDS = [
+export const REGISTER_FIELDS = (getValues: UseFormGetValues<FieldValues>) => [
   {
     placeholder: 'Почта',
     name: 'email',
@@ -48,10 +49,7 @@ export const REGISTER_FIELDS = [
     name: 'confirm_password',
     type: 'password',
     validate: (value = '') => {
-      const password = document.querySelector(
-        'input[name="password"]'
-      ) as HTMLInputElement;
-      if (password.value !== value) {
+      if (getValues('password') !== value) {
         return 'Пароли не совпадают';
       }
```

2023-03-04 18:28 UTC, DNLHC commented on packages/client/src/mock/register-fields.ts
> +export const LOGIN_FIELDS = [
Файл `mock` точно удачное место для таких данных? Обычно в моках лежат статичные данные для временного вывода без АПИ.

2023-03-04 21:05 UTC, Aleksa-esme commented on packages/client/src/mock/register-fields.ts
> +export const LOGIN_FIELDS = [
тут временно, планировала перенести на страницы логина и регистрации. Если форму лучше поделить на две, то перенесу эти данные в них

2023-03-05 06:32 UTC, alex-kurkov commented on packages/client/src/mock/register-fields.ts
> +export const LOGIN_FIELDS = [
Нам надо, наверно, завести какой-то конфиг для статичных данных, или потом в стор это положим?

2023-03-05 06:33 UTC, alex-kurkov approved these changes

2023-03-06 22:35 UTC, DNLHC approved these changes

2023-03-06 22:35 UTC, DNLHC commented on packages/client/src/components/form/login-form.tsx
> +        key="password"
ключи можно удалить, итерации нету

2023-03-06 22:54 UTC, DNLHC commented on packages/client/src/components/form/login-form.tsx
> +    reset();
Нам точно нужно ресетить форму? При успешном логине будет редирект на главную, и при ошибке так делать странно.

2023-03-07 09:11 UTC, mozg3000 approved these changes
Обновить ветку наверное нужно только.

2023-03-07 11:15 UTC, Marmeloy approved these changes

2023-03-07 11:38 UTC, EzhikTT approved these changes
Все ок

2023-03-07 11:59 UTC, merged