добавил глобальные классы и css-переменные
Fancy-Colors/FCG-Fancy-Colors-Game pull request #3
Opened 2023-02-23 13:21 UTC by alex-kurkov

1. w-1 w-2 w-3 w-4 w-6 w-12 - ширина, соответсвующая количеству колонок в 12-ти колоночной сетке (до 1440 считается от вьюпорта, выше - от 1440) 
2. Css-переменные для цветов (названия переменных как в фигме)
3. Глобальные классы для текста (size+weight+line-height) (названия классов как в фигме)

2023-02-23 17:02 UTC, DNLHC requested changes

2023-02-23 17:02 UTC, DNLHC commented on packages/client/src/styles/layout.pcss
> +/* stylelint-disable */
Не стоит полностью отключать линтер из-за одного правила, лучше явно указать это правило
`/* stylelint-disable selector-class-pattern */`

2023-02-23 17:02 UTC, DNLHC commented on packages/client/src/styles/typography.pcss
> +/* stylelint-disable */
тут тоже

2023-02-24 09:43 UTC, mozg3000 approved these changes

2023-02-24 13:59 UTC, Aleksa-esme approved these changes

2023-02-24 14:35 UTC, Marmeloy approved these changes

2023-02-24 15:38 UTC, merged