layout/forum-message/87
Fancy-Colors/FCG-Fancy-Colors-Game pull request #30
Opened 2023-03-04 12:15 UTC by mozg3000

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-04 12:23 UTC, mozg3000 commented
Черновой вариант

2023-03-04 18:57 UTC, DNLHC requested changes

2023-03-04 18:57 UTC, DNLHC commented on packages/client/src/components/forum-message/forum-message.module.pcss
> +  &Avatar {
почему не сделать просто `avatar` вместо `messageAvatar`, у нас css-модули решают проблему уникальности пространства имён классов, не вижу необходимости так делать.
Это касается всех классов в компоненте.

2023-03-04 18:57 UTC, DNLHC commented on packages/client/src/components/forum-message/forum-message.tsx
> +        <Avatar avatar={avatar} name={name} size={'small'} />
```suggestion
        <Avatar avatar={avatar} name={name} size='small' />
```
можно без скобок

2023-03-04 18:57 UTC, DNLHC commented on packages/client/src/components/forum-message/forum-message.tsx
> +        <h5 className={style.messageContentDate}>{date}</h5>
Для даты в HTML есть тег `<time>`

2023-03-04 18:57 UTC, DNLHC commented on packages/client/src/components/forum-message/forum-message.tsx
> +        <div className={style.messageContentText}>{text}</div>
тут подходит элемент `<p>`

2023-03-04 18:57 UTC, DNLHC commented on packages/client/src/components/forum-message/forum-message.tsx
> +      </div>
Разве это не кнопка reply? Почему через `div`?

2023-03-04 18:57 UTC, DNLHC commented on packages/client/src/components/forum-message/forum-message.module.pcss
> +@import 'src/styles/variables.pcss';
Переменные импортировать не нужно, они глобальны

2023-03-05 06:28 UTC, alex-kurkov requested changes

2023-03-05 06:28 UTC, alex-kurkov commented on packages/client/src/components/forum-message/forum-message.tsx
> +        <h5 className={style.messageContentDate}>{date}</h5>
У нас есть компонент `DateFormatted`, который переводит дату из формата, в котором она приходит с бэка в нужный нам

2023-03-05 06:28 UTC, alex-kurkov commented on packages/client/src/components/forum-message/forum-message.tsx
> +        <div className={style.messageContentText}>{text}</div>
для стилизации текста есть глобальные классы

2023-03-05 06:28 UTC, alex-kurkov commented on packages/client/src/components/forum-message/forum-message.tsx
> +export { ForumMessage };
можно export перенести выше: `export const ForumMessage: FC<Forum...` (это не то, чтобы правильно, но во всех других компонентах мы до этого писали именно так - при объявлении константы, поэтому для консистентности лучше делать так же)

2023-03-06 04:27 UTC, alex-kurkov approved these changes

2023-03-06 15:10 UTC, Aleksa-esme commented on packages/client/src/components/forum-message/forum-message.tsx
> +        <div className={cn('text-main', style.date)}>
ты используешь стиль text-main, который уже содержит стили 
` font-size: 16px;`
 `line-height: 1.2;`
их можно убрать из стиля date и оставить в нем только `color: var(--color-medium);`

2023-03-06 15:12 UTC, Aleksa-esme approved these changes

2023-03-06 15:14 UTC, Aleksa-esme commented on packages/client/src/components/forum-message/forum-message.tsx
> +          <Icon type="enter" size="xs" color={'#6d7076'} />
лучше так `color="#6d7076"`

2023-03-06 21:54 UTC, DNLHC approved these changes

2023-03-07 11:16 UTC, Marmeloy approved these changes

2023-03-07 11:39 UTC, EzhikTT approved these changes
Все ок

2023-03-07 12:02 UTC, merged