Lib/game page
Fancy-Colors/FCG-Fancy-Colors-Game pull request #31
Opened 2023-03-04 14:56 UTC by alex-kurkov

Базовый игровой экран (заготовка) + игровой движок

##TBD
- оптимизации
- расширение игрового поля 
- клик при зуме
- экран выхода
- счет и время
- история ходов

2023-03-06 04:01 UTC, DNLHC requested changes

2023-03-06 04:02 UTC, DNLHC commented
Круто работает :thumbsup:

2023-03-07 06:14 UTC, DNLHC requested changes
Работает хорошо, я предлагаю залить текущую реализацию в main (после того, как все заапрувят), и продолжить работу над игрой в след. итерации, когда страница с игрой будет внедрена в общий лэйаут.

2023-03-07 09:31 UTC, mozg3000 approved these changes

2023-03-07 11:41 UTC, EzhikTT approved these changes
Все ок

2023-03-07 16:00 UTC, Aleksa-esme approved these changes

2023-03-07 22:07 UTC, DNLHC approved these changes

2023-03-07 22:07 UTC, merged