layout/forum-thread/86
Fancy-Colors/FCG-Fancy-Colors-Game pull request #32
Opened 2023-03-04 16:53 UTC by mozg3000

### Какую задачу решаем

Отображание страницы треда на форуме.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-04 19:18 UTC, DNLHC requested changes

2023-03-04 19:18 UTC, DNLHC commented on packages/client/src/components/forum-thread/forum-thread.module.pcss
> +.backBox {
Странное название класса, почему box?

2023-03-04 19:18 UTC, DNLHC commented on packages/client/src/components/forum-thread/forum-thread.tsx
> +          <div className={style.threadHeader}>{thread.title}</div>
Почему заголовок поста называется `threadHeader` и почему через `div`, может лучше `title`?

2023-03-04 19:18 UTC, DNLHC commented on packages/client/src/components/forum-thread/forum-thread.tsx
> +        <div className={style.backBox}>
тут div обёртка точно нужна?

2023-03-04 19:40 UTC, mozg3000 commented on packages/client/src/components/forum-thread/forum-thread.module.pcss
> +.backBox {
не придумал ничего другог)) есть альтернатива?

2023-03-04 19:53 UTC, DNLHC commented on packages/client/src/components/forum-thread/forum-thread.tsx
> +          <div className={style.threadHeader}>{thread.title}</div>
Я про название класса threadHeader, почему не назвать заголовок заголовком?)
И поставить соответствующий тег.

2023-03-04 19:55 UTC, DNLHC commented on packages/client/src/components/forum-thread/forum-thread.module.pcss
> +.backBox {
`goBack`, `goBackLink`, `toThreadsLink`

2023-03-05 07:21 UTC, alex-kurkov requested changes

2023-03-05 07:21 UTC, alex-kurkov commented on packages/client/src/components/forum-message/forum-message.module.pcss
> +@import 'src/styles/variables.pcss';
не нужен импорт - этот stylesheet уже импортирован на уровне `main.tsx`

2023-03-05 07:21 UTC, alex-kurkov commented on packages/client/src/components/forum-thread/forum-thread.tsx
> +          <div className={style.threadHeader}>{thread.title}</div>
тут и heading-тег подойдет

2023-03-05 07:21 UTC, alex-kurkov commented on packages/client/src/mock/forum-thread.ts
> +      date: 'Feb 21 2023',
при использовании готового компонента DateFormatted тут надо строку с датой привести к состоянию - "как приходит с бэка"

2023-03-05 18:48 UTC, DNLHC requested changes

2023-03-05 18:48 UTC, DNLHC commented on packages/client/src/components/forum-thread/forum-thread.module.pcss
> +}
У тебя иконка стрелки не выровнена относительно текста в ссылке
 ```suggestion
.link {
  color: var(--color-accent-primary);
  padding-bottom: 24px;
  display: inline-flex;
  align-items: center;
}
```

2023-03-05 18:48 UTC, DNLHC commented on packages/client/src/components/forum-message/forum-message.module.pcss
> +}
Стоит добавить кнопке `cursor: pointer`, для индикации интерактивности на ховере

2023-03-05 18:48 UTC, DNLHC commented on packages/client/src/components/forum-message/forum-message.module.pcss
> +  flex-wrap: nowrap;
Аватарка автора поста центрируется относительно сообщения, а должна выравниваться по верхнему краю, нужно добавить `align-items: flex-start;`

2023-03-06 05:23 UTC, alex-kurkov approved these changes

2023-03-06 05:40 UTC, Aleksa-esme commented on packages/client/src/components/forum-message/forum-message.tsx
> +        <button className={style.reply} type="button" onClick={onClickHandler}>
нужно заменить на компонент Button с color 'icon' и size 'small'

2023-03-06 05:41 UTC, Aleksa-esme commented on packages/client/src/components/forum-message/forum-message.module.pcss
> +}
если добавить Button, то этот стиль вообще не нужен

2023-03-06 05:49 UTC, Aleksa-esme commented on packages/client/src/components/forum-message/forum-message.tsx
> +        <div className={style.date}>
У нас есть файл со стилями текстов typography.pcss, можно совмещать общие стили и твои:
import cn from 'classnames';
<div className={ cn(style.date}, 'text-main') }>

2023-03-06 15:22 UTC, Aleksa-esme commented on packages/client/src/components/forum-thread/forum-thread.module.pcss
> +  padding-top: 24px;
у нас значение этого отступа много где используется по проекту, оно вынесено в отдельную переменную `--gap: 24px;` в файле variables.pcss, лучше заменить на `padding-top: var(--gap);` , что бы потом при адаптивной верстке это значение поменялось везде. Далее по файлу так же нужно его поправить

2023-03-06 21:55 UTC, DNLHC approved these changes

2023-03-07 11:17 UTC, Marmeloy approved these changes

2023-03-07 11:42 UTC, EzhikTT approved these changes
Все ок

2023-03-07 12:11 UTC, DNLHC approved these changes

2023-03-07 22:08 UTC, merged