Lib/RegisterLoginPage/15
Fancy-Colors/FCG-Fancy-Colors-Game pull request #35
Opened 2023-03-05 14:49 UTC by Aleksa-esme

2023-03-07 11:54 UTC, EzhikTT requested changes

2023-03-07 11:54 UTC, EzhikTT commented on packages/client/src/components/form/login-form.tsx
> +export const LoginForm: FC = ({ ...props }) => {
А в чем смысл деструктуризации такой? Все равно жеж объект приходит

2023-03-07 14:37 UTC, Aleksa-esme commented on packages/client/src/components/form/login-form.tsx
> +export const LoginForm: FC = ({ ...props }) => {
что бы в форму можно было передать ее пропсы которые не указаны в компоненте 
`<form className={styles.form} onSubmit={handleSubmit(onSubmit)} {...props}>`

Исправила типизацию формы на
`type Props = JSX.IntrinsicElements['form'];`
`export const RegisterForm: FC<Props> = ({ ...props }) => {`

2023-03-08 06:36 UTC, alex-kurkov approved these changes

2023-03-08 06:36 UTC, alex-kurkov commented on packages/client/src/pages/register-login/login.tsx
> +              <div>
нет ли тут лишнего `div`?)

2023-03-08 06:36 UTC, alex-kurkov commented on packages/client/src/pages/register-login/register-login.module.pcss
> +  background: rgba(255, 255, 255, 0.9);
может тоже в `variables.css` добавить цвет? Когда будем внедрять темизацию будет проще

2023-03-08 06:36 UTC, alex-kurkov commented on packages/client/src/pages/register-login/register.tsx
> +              <div>
тот же extra-div?

2023-03-08 07:54 UTC, Aleksa-esme commented on packages/client/src/pages/register-login/register.tsx
> +              <div>
могу убрать, но там иначе у лого высота большая без него получается
![2023-03-08_10-52-24](https://user-images.githubusercontent.com/58600329/223653920-398d0a78-f330-4d19-a7f6-68052797031a.png)
![2023-03-08_10-51-13](https://user-images.githubusercontent.com/58600329/223653941-247aa74d-f66f-43d4-954c-076af3314082.png)
![2023-03-08_10-51-54](https://user-images.githubusercontent.com/58600329/223653954-2fb58dec-660d-4f42-a2b6-4d94e06c9362.png)

2023-03-08 09:32 UTC, DNLHC commented on packages/client/src/pages/register-login/register.tsx
> +              <div>
от двух-трёх обёрток точно избавиться можно
а почему лого не поставить нужную ширину, чтобы высота сама подстраивалась по соотношению сторон? у тебя стоит 100%/100%

2023-03-08 13:30 UTC, DNLHC approved these changes
Всё отлично, но стоит попробовать избавиться от лишних обёрток

2023-03-09 09:24 UTC, EzhikTT approved these changes
Все ок

2023-03-10 06:54 UTC, merged