добавляет хук useFullScreen
Fancy-Colors/FCG-Fancy-Colors-Game pull request #40
Opened 2023-03-10 08:14 UTC by alex-kurkov

### Какую задачу решаем
- добавлен хук `useFullScreen` и компонент `FullScreenButton`. В хук не обязательно передавать конкретный элемент для перевода в fullscreen, тогда переведется `documentElement`
- на всякий случай хук возвращает как состояние isFullscreen, так и три метода `toggleFullScreen, open, close`

### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/65237410/224259757-98615112-e3ee-405d-95a9-8503b454214c.mp4

### TBD
- сделать тоглер кнопкой-иконкой

2023-03-10 08:23 UTC, Aleksa-esme approved these changes

2023-03-10 08:23 UTC, Aleksa-esme commented on packages/client/src/components/fullscreen-button/fullscreen-button.tsx
> +    if (e.key === 'f') {
нужно где то указать на странице (может рядом с кнопкой), что в этот режим можно перейти по нажатию F

2023-03-11 05:10 UTC, DNLHC requested changes

2023-03-11 05:10 UTC, DNLHC commented on packages/client/src/components/hooks/use-fullscreen.ts
> +const dEl = d.documentElement as VendorElement;
Я бы предложил избавиться от сокращений `d`, `dEl`, `fsEl`, такой код сложней читать и понимать.

2023-03-11 05:10 UTC, DNLHC commented on packages/client/src/components/hooks/use-fullscreen.ts
> +      d.removeEventListener('fullscreenchange', handleChange);
Лучше передавать все аргументы переданные при регистрации эвента (здесь отсутствует `useCapture`), иначе при удалении эвент может некорректно сматчиться, в нашем случае это маловероятно, но всё-же лучше всегда передавать идентичные аргументы.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#matching_event_listeners_for_removal

2023-03-11 08:58 UTC, mozg3000 approved these changes

2023-03-11 15:02 UTC, Marmeloy approved these changes

2023-03-13 06:23 UTC, EzhikTT commented on packages/client/src/components/hooks/use-fullscreen.ts
> +      vendorDocument.fullscreenElement === el ||
Лучше расставить от более частого к менее. По идее, вторым должен быть вебкит

2023-03-13 06:23 UTC, EzhikTT approved these changes
Все ок

2023-03-13 16:09 UTC, merged