Экран и логика окончания игры
Fancy-Colors/FCG-Fancy-Colors-Game pull request #42
Opened 2023-03-12 14:13 UTC by alex-kurkov

### Какую задачу решаем
- добавлена логика подсчета очков, запись истории ходов и экран завершения игры
- оптимизированы процессы
- введена сортировка цветов
- изменена базовая игровая картинка
- некоторая логика вынесена в utils

### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/65237410/224550225-d21ffcfd-c803-4a55-9a75-cd2684ee93da.mp4

2023-03-12 14:47 UTC, mozg3000 approved these changes

2023-03-13 06:28 UTC, EzhikTT requested changes

2023-03-13 06:28 UTC, EzhikTT commented on packages/client/src/components/game-view/utils/resize-field.ts
> +    width - 24,
`24` - всегда такое? Мб лучше в константу вынести?

2023-03-13 15:58 UTC, Aleksa-esme approved these changes

2023-03-13 21:55 UTC, DNLHC requested changes

2023-03-13 21:55 UTC, DNLHC commented on packages/client/src/components/game-timer/game-timer.tsx
> +  }, [seconds]);
Тут вижу две проблемы:
1. На каждое изменение `seconds` хук будет очищаться и заново запускаться, пересоздавая интервал, хотя нам нужно начать интервал только один раз.
2. Когда стейт апдейтится на основе предыдущего значения - могут [возникнуть проблемы](https://beta.reactjs.org/reference/react/useState#updating-state-based-on-the-previous-state) (нужно делать через коллбэк)

Лучше сделать так:
```diff
diff --git a/packages/client/src/components/game-timer/game-timer.tsx b/packages/client/src/components/game-timer/game-timer.tsx
index b3b170a..7868a1c 100644
--- a/packages/client/src/components/game-timer/game-timer.tsx
+++ b/packages/client/src/components/game-timer/game-timer.tsx
@@ -10,12 +10,12 @@ export const GameTimer: FC<{
 
   useEffect(() => {
     const intervalId = setInterval(() => {
-      setSeconds(seconds + 1);
+      setSeconds((currentSeconds) => currentSeconds + 1);
     }, 1000);
     return () => {
       clearInterval(intervalId);
     };
-  }, [seconds]);
+  }, []);
 
   useEffect(() => {
     setTimeElapsed(seconds);
```

2023-03-13 21:55 UTC, DNLHC commented on packages/client/src/components/game-view/game-view-completed.tsx
> +        <span onClick={playAgain} className={styles.accent}>
почему не кнопкой? Такой элемент нельзя зафокусить или затриггирить через `space`/`enter`

2023-03-13 21:55 UTC, DNLHC commented on packages/client/src/components/game-timer/game-timer.tsx
> +  }, [seconds, setTimeElapsed]);
Почему не вынести логику отсчёта в родительский компонент, а этот сделать "тупым"? Не пришлось бы делать такую странную синхронизацию

2023-03-13 21:55 UTC, DNLHC commented on packages/client/src/components/game-view/game-view-completed.tsx
> +      <Message />
Лучше дать название конкретней, не ясно что за Message такой
например: `EndGameMessage`

2023-03-13 21:55 UTC, DNLHC commented on packages/client/src/components/game-view/game-view-completed.tsx
> +      <p className={cn('text-main', styles.paragraph)}>
Просто интересно, почему решил вынести компонент так?

2023-03-13 21:55 UTC, DNLHC commented on packages/client/src/components/game-view/game-view-completed.tsx
> +export const GameViewCompleted: FC<Props> = ({ data, user, playAgain }) => {
`data` слишком общее название для переменной, со стороны читая код сложно понять что в нём хранится и для чего.

2023-03-13 21:55 UTC, DNLHC commented on packages/client/src/components/game-view/game-view-completed.tsx
> +/* eslint-disable react-hooks/exhaustive-deps */
лучше не отрубать правила глобально, а ставить там, где необходимо, в других местах он может предотвратить ошибку.
Знаю, что `exhaustive-deps` правило слишком назойливое, но полностью отрубать его не стоит, тут хороший [ответ Дэна Абрамова](https://github.com/facebook/create-react-app/issues/6880#issuecomment-485912528)

2023-03-13 21:55 UTC, DNLHC commented on packages/client/src/pages/game/game.tsx
> +  secondName: 'SURNAME',
Авторизация уже есть, можно достать реального юзера через `const { user } = useAuth();`

2023-03-13 23:49 UTC, Marmeloy approved these changes

2023-03-14 13:49 UTC, EzhikTT approved these changes
Все ок

2023-03-14 15:13 UTC, alex-kurkov commented on packages/client/src/components/game-view/game-view-completed.tsx
> +      <p className={cn('text-main', styles.paragraph)}>
Для небольшой разгрузки основной разметки компонента - ну и сам текст насыщен интерактивными элементами и вполне может измениться с течением времени.

2023-03-14 22:14 UTC, DNLHC approved these changes

2023-03-14 22:14 UTC, DNLHC commented on packages/client/src/components/game-view/game-view-completed.tsx
> +        </Button>
Я имел ввиду сделать через элемент `<button>` вместо `<span> и стилизовать как тебе нужно, тут сам смотри

2023-03-15 03:22 UTC, merged