Feat/new game fields/57
Fancy-Colors/FCG-Fancy-Colors-Game pull request #43
Opened 2023-03-12 16:09 UTC by alex-kurkov

### Какую задачу решаем
- добавлено три реальных картинки для игры
- логика перенесена на уровень main
- зависит от (PR)[https://github.com/Fancy-Colors/FCG-Fancy-Colors-Game/pull/42]

### Скриншоты/видяшка (если есть)
![Скриншот 12-03-2023 19_09_33](https://user-images.githubusercontent.com/65237410/224557336-c582b260-27af-4673-b9f6-93c8ddbc7869.jpg)

### TBD (если есть)

2023-03-13 06:41 UTC, EzhikTT approved these changes
Все ок

2023-03-13 15:58 UTC, Aleksa-esme approved these changes

2023-03-13 16:05 UTC, mozg3000 approved these changes

2023-03-13 22:11 UTC, DNLHC requested changes

2023-03-13 22:11 UTC, DNLHC commented on packages/client/src/utils/make-cards-list.ts
> +type ReturnType = {
в TS есть утилитарный тип с аналогичным названием [`ReturnType`](https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype), лучше дать уникальное название

2023-03-13 22:11 UTC, DNLHC commented on packages/client/src/utils/make-cards-list.ts
> +type ReturnType = {
По названию, функция создаёт `cardList`, значит и возвращать должна `CardList`, кстати, почему у нас все типы с окончанием `Type`, оно точно нужно?

2023-03-13 23:48 UTC, Marmeloy approved these changes

2023-03-14 22:14 UTC, DNLHC approved these changes

2023-03-15 05:11 UTC, merged