feature/forum-redux/118
Fancy-Colors/FCG-Fancy-Colors-Game pull request #51
Opened 2023-03-17 10:45 UTC by mozg3000

### Какую задачу решаем

Добавляет использование  redux на странице форума.
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-17 11:26 UTC, Aleksa-esme commented on packages/client/src/pages/forum/forum.tsx
> +  useEffect(() => {
можно попробовать переписать как то так, что бы eslint не ругался
`useEffect(() => {`
    `const fetchData = async () => {`
      `try {`
        `if (!(page in forum)) {`
          `const data = await client.getForum(page);`
          `dispatch(setForum({page, data}));`
       ` }`
     ` } catch (e) {`
       `console.log(e);`
      `}`
    `}`
    `fetchData();`
 `}, [page, dispatch, forum]);`

2023-03-17 11:27 UTC, EzhikTT commented on packages/client/src/components/game-view/game-view-completed.tsx
> +    (state) => state.game.completedGame
А почему не в одну строчку? Мб сделаете допустимую длину строчки 120?

2023-03-17 11:30 UTC, EzhikTT commented on packages/client/src/pages/forum/forum.tsx
> +  useEffect(() => {
Мб можно на `async/await` переписать и не будет ругаться? `(async () => { .... })()`

2023-03-17 11:47 UTC, mozg3000 commented
Там ТС ругается на тип который принимает useEffect. await возвращает просим, а это не то что ждёт useEffect. 14:31, 17 марта 2023 г., Alexander Petruhin ***@***.***>:
@EzhikTT commented on this pull request.



In packages/client/src/pages/forum/forum.tsx:
>  
 export const Forum = () => {
   const [page, setPage] = useState(1);
-  // eslint-disable-next-line @typescript-eslint/no-unused-vars
-  const [count, setCount] = useState(20);
+  const { forum, count } = useAppSelector((state) => state.forum);
+  const dispatch = useAppDispatch();
+
+  useEffect(() => {

Мб можно на async/await переписать и не будет ругаться? (async () => { .... })()

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

2023-03-17 12:13 UTC, EzhikTT requested changes

2023-03-17 12:13 UTC, EzhikTT commented on packages/client/src/pages/forum/forum.tsx
> +            ) // не знаю как там через thunk это сделать - поэтому так.
А можно посмотреть что пытались сделать? Через `createAsyncThunk` создать и передать в `dispatch`?

2023-03-17 13:11 UTC, mozg3000 commented on packages/client/src/pages/forum/forum.tsx
> +            ) // не знаю как там через thunk это сделать - поэтому так.
Я просто не представляю как это сделать с thunk. У меня асинхронный запрос к апи и мне нужно положить результат в store. Сейчас у меня это делается просто через вызов action, а как это проделать с thunk я не знаю.

2023-03-17 13:13 UTC, mozg3000 commented on packages/client/src/pages/forum/forum.tsx
> +            ) // не знаю как там через thunk это сделать - поэтому так.
я так понимаю, что нужно использовать этот код из файла store.ts
```
export type AppThunk<ReturnType = void | Promise<unknown>> = ActionCreator<
  ThunkAction<ReturnType, RootState, unknown, AnyAction>
>;
```

2023-03-17 16:24 UTC, mozg3000 commented on packages/client/src/pages/forum/forum.tsx
> +  useEffect(() => {
> можно попробовать переписать как то так, `
предвидя thunk не стал выдумывать))

2023-03-17 16:26 UTC, mozg3000 commented on packages/client/src/pages/forum/forum.tsx
> +            ) // не знаю как там через thunk это сделать - поэтому так.
> А можно посмотреть что пытались сделать? Через `createAsyncThunk` создать и передать в `dispatch`?

коллеги подсказали, сделал с использованием thunk. теперь там нет потребности в await.

2023-03-17 18:03 UTC, DNLHC requested changes

2023-03-19 21:42 UTC, DNLHC requested changes
В остальном всё хорошо

2023-03-19 21:42 UTC, DNLHC commented on packages/client/src/api/forum.ts
> +import { ForumItem as ForumItemProps } from 'src/services/reducers/forum-slice';
Нужно убрать папку `reducers` и положить слайс в корень `services`, посмотри как у Алексея в ПР сделано.

2023-03-19 21:42 UTC, DNLHC commented on packages/client/src/api/forum.ts
> +    return new Promise<Array<ForumItemProps>>((resolve) => {
```suggestion
  ): Promise<ForumItemProps[]> => {
    return new Promise<ForumItemProps[]>((resolve) => {
```
можно упростить синтаксис

2023-03-19 21:42 UTC, DNLHC commented on packages/client/src/services/reducers/forum-slice.ts
> +        data: Array<ForumItem>;
упростить массив через `ForumItem[]`

2023-03-20 13:00 UTC, EzhikTT approved these changes
Все ок

2023-03-20 22:51 UTC, DNLHC approved these changes

2023-03-21 15:57 UTC, Aleksa-esme approved these changes

2023-03-22 02:52 UTC, Marmeloy approved these changes

2023-03-22 14:42 UTC, merged