адаптация лидерборда и сайдменю под мобильные устройства
Fancy-Colors/FCG-Fancy-Colors-Game pull request #53
Opened 2023-03-20 12:58 UTC by Aleksa-esme

- Исправлен скролл на странице
- Добавлена логика отображения сайд меню
- Компоненты, использующие данные с сервера, обернуты в ErrorBoundary
- Адаптация под мобильные устройства
![2023-03-20_15-42-51](https://user-images.githubusercontent.com/58600329/226345248-f227af04-04b1-47f2-80cd-45a7f6c978bd.png)
![2](https://user-images.githubusercontent.com/58600329/226346412-e654100d-35a7-4b4c-b18a-9df29a3f917d.jpg)

2023-03-20 13:08 UTC, EzhikTT approved these changes
Все ок

2023-03-20 16:53 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.tsx
> +  });
В зависимости `useEffect` передан `undefined` (второй параметр), из-за чего он будет перевыполняться на каждый ререндер компонента (полагаю, так не было задумано), следует указать пустой массив зависимостей `[]`

2023-03-20 16:53 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.module.pcss
> +    transition: left 0.3s;
лучше не использовать `left`, `top`, `bottom`, `right` для анимаций, т.к они вызывают репэинт и вычисляются на ЦПУ, `translate()` в свою очередь вычисляется через GPU и для него выделяется отдельный слой, не влияющий на другие слои.
[тут почитать подробней](https://web.dev/animations-guide/#force)

2023-03-20 16:53 UTC, DNLHC commented on packages/client/src/styles/utils.pcss
> +}
с `postcss-nested` медиа-запросы можно вкладывать в селекторы
```css
.u-fancy-scrollbar {
  ...

  @media (max-width: 450px) {
    &::-webkit-scrollbar {
      width: 4px;
      height: 4px;
    }
  }
}
```

2023-03-21 16:39 UTC, EzhikTT requested changes
Исправьте все внутренние замечания

2023-03-22 10:01 UTC, Aleksa-esme commented on packages/client/src/styles/utils.pcss
> +}
Исправила все замечания выше, но медиа не стала вкладывать в селекторы. Мне удобнее видеть все медиа запросы отдельно от основных стилей, а не когда они разбросаны по всему файлу

2023-03-22 13:38 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.module.pcss
> -  color: var(--color-accent-primary);
По умолчанию компонент `Icon` ставит цвет заливки/обводки иконки значение `currentColor` - это ключевое слово, которое наследует цвет текста родителя, с помощью него удобно управлять множеством разных цветовых свойств через одно родительское свойство `color`. Здесь можно было не менять на `fill`

2023-03-22 13:38 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.module.pcss
> +    display: none;
Зачем здесь `display: none` если ниже в обоих случаях (при `.hide` и `.show`) стоит `display: flex`?

2023-03-22 13:38 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.module.pcss
> +      transform: translateX(-1000px);
В таких случаях лучше не использовать абсолютные значения (1000px). Скорость анимации трансформа будет не совсем корректная.

2023-03-22 13:38 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.tsx
> +      }
Обычно в реакте нет необходимости напрямую работать с классами DOM, разве тут нельзя было сделать всё через стейт?

2023-03-22 14:51 UTC, alex-kurkov approved these changes
Ок, но я бы сделал отдельный компонент burgerMenu а не расширял итак не маленький sideMenu, сейчас он с разбухшей логикой уже не очень хорошо воспринимается, несмотря на то, что сам его когда-то писал)

2023-03-23 12:18 UTC, DNLHC approved these changes
Всё хорошо

2023-03-23 12:18 UTC, DNLHC commented on packages/client/src/components/side-menu/side-menu.tsx
> +  }, [location, path]);
тут `setPath` точно нужен? По-моему можно упростить
```diff
diff --git a/packages/client/src/components/side-menu/side-menu.tsx b/packages/client/src/components/side-menu/side-menu.tsx
index 4223a85..af5dadf 100644
--- a/packages/client/src/components/side-menu/side-menu.tsx
+++ b/packages/client/src/components/side-menu/side-menu.tsx
@@ -23,7 +23,6 @@ export const SideMenu: FC = () => {
 
   const [expanded, setExpanded] = useState(true);
   const [isVisible, setIsVisible] = useState(false);
-  const [path, setPath] = useState(location.pathname);
 
   const handleMenuOpen = useCallback(() => {
     if (width > 500) {
@@ -35,11 +34,8 @@ export const SideMenu: FC = () => {
   }, [expanded, isVisible, width]);
 
   useEffect(() => {
-    if (path !== location.pathname) {
-      setIsVisible(false);
-      setPath(location.pathname);
-    }
-  }, [location, path]);
+    setIsVisible(false);
+  }, [location.pathname]);
 
   useEffect(() => {
     if (width >= 500 && width < 1024) {
```

2023-03-27 07:00 UTC, Marmeloy approved these changes

2023-03-27 10:20 UTC, merged