feature/thread-redux/120
Fancy-Colors/FCG-Fancy-Colors-Game pull request #54
Opened 2023-03-21 18:06 UTC by mozg3000

### Какую задачу решаем
Добавляет использование redux на странице темы (треда)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-22 17:13 UTC, DNLHC commented on packages/client/src/pages/forum-thread/forum-thread.tsx
> +  }
Тебя скорей всего не перекинет на этот роут без `threadId`, т.к такой путь просто не сматчится в `react-router`
Такие ошибки лучше обрабатывать редиректом на 404

2023-03-22 17:13 UTC, DNLHC commented on packages/client/src/services/forum-slice.ts
> +};
Странная структура, у нас скорей всего будут приходить обычные массивы с тредами, почему здесь сделано через объекты с ключами айдишников?

2023-03-23 08:30 UTC, EzhikTT commented on packages/client/src/api/forum.ts
> +    return new Promise<Thread>((resolve) => {
Можно было в одну строчку записать

2023-03-23 08:38 UTC, EzhikTT requested changes

2023-03-23 08:38 UTC, EzhikTT commented on packages/client/src/services/forum-slice.ts
> +      state.threads = {
У вас слайсы, не нужно копировать полностью старый объект, чтобы сделать новый. Должно быть достаточно обновить/добавить по ключу в карте данные

2023-03-23 08:38 UTC, EzhikTT commented on packages/client/src/services/forum-slice.ts
> +};
По карте быстрый обход, если в нее превращать массив. Почему `id` трейда может быть разных типов? Весь смысл карты теряется

2023-03-27 17:35 UTC, EzhikTT requested changes
Открытые треды надо порешать

2023-04-11 14:59 UTC, EzhikTT requested changes

2023-04-14 04:05 UTC, Aleksa-esme approved these changes

2023-04-14 13:51 UTC, EzhikTT approved these changes
Все ок

2023-04-18 15:20 UTC, merged