Layout/profile mobile/121
Fancy-Colors/FCG-Fancy-Colors-Game pull request #56
Opened 2023-03-24 12:09 UTC by Aleksa-esme

Добавлен скролл на странице
Компоненты, использующие данные с сервера, обернуты в ErrorBoundary
Адаптация под мобильные устройства
![2](https://user-images.githubusercontent.com/58600329/227517498-552feaa3-af5b-4219-9a8a-5aa253c7de72.jpg)

2023-03-24 20:05 UTC, DNLHC approved these changes
Всё хорошо

2023-03-26 06:42 UTC, Aleksa-esme commented on packages/client/src/pages/profile/profile.tsx
> +            <ErrorBoundary>
мне кажется, что дополнительная обработка компонентов, которые отображают данные, полученные с сервера, лишней не будет. Поправь, пожалуйста, если это не так

2023-03-26 17:02 UTC, DNLHC commented on packages/client/src/pages/profile/profile.tsx
> +            <ErrorBoundary>
Если одно поле отрендерит ошибку, то и вся форма без этого поля станет неюзабельна. Кажется, имеет смысл обернуть сразу всю форму со сломанным инпутом.
[Хорошая статься](https://aweary.dev/fault-tolerance-react/) на этот счет (реакт доки на неё ссылаются)
У нас здесь две независимые формы `PasswordForm`, `ProfileForm` - их можно обернуть отдельно друг от друга.

2023-03-27 07:01 UTC, Marmeloy approved these changes

2023-03-27 10:23 UTC, alex-kurkov approved these changes
Ок!

2023-03-27 17:37 UTC, EzhikTT commented on packages/client/src/components/leader/leader.tsx
> +      {size === 'row' && (
А в одну строчку оно не умещается?

2023-03-27 17:43 UTC, EzhikTT requested changes

2023-03-27 17:43 UTC, EzhikTT commented on packages/client/src/components/side-menu/side-menu.tsx
> +    } else if (width < 500) {
`else if` и `else` нельзя объединить в одно условие?

2023-03-27 18:01 UTC, Aleksa-esme commented on packages/client/src/components/leader/leader.tsx
> +      {size === 'row' && (
у нас автоматический перенос под длину строки

2023-03-27 18:08 UTC, Aleksa-esme commented on packages/client/src/components/side-menu/side-menu.tsx
> +      setIsVisible(!isVisible);
ниже срабатывает при клике на ссылки, там меню при изменении пути должно скрываться. Тут оно скрывается когда пользователь сам жмет на кнопку. У нас меню на большом экране имеет два вида: широкое с подписями иконок и узкое без подписей, а на маленьком экране оно всегда должно быть с подписями, но само меню должно либо полностью скрываться либо быть шириной на весь экран

2023-04-02 14:31 UTC, EzhikTT approved these changes
Все ок

2023-04-03 15:50 UTC, merged