АПИ лидерборда + редакс
Fancy-Colors/FCG-Fancy-Colors-Game pull request #57
Opened 2023-03-28 13:08 UTC by Aleksa-esme

- Добавлен АПИ лидерборда
- Вывод игроков на странице лидерборда
- Добавление/обновление пользователя в списке игроков 
- Отправка данных о пользователе по окончании игры

P.S. 
1. При деплое нужно будет поменять название команды
2. Так же апишка несколько кривая(хотя может это не баг, а фича) - если засабмитить с ваших текущих учеток данные в  эту команду ( const TEAM_NAME = 'test_colors' ), то больше ни в какую другую команду они добавляться не будут
![2023-03-27_12-56-35](https://user-images.githubusercontent.com/58600329/228244746-720a51e0-9d86-4a8f-b6ab-d69c0a046855.png)

2023-03-29 17:14 UTC, DNLHC commented on packages/client/src/actions/leaderboard.ts
> +    const player = (leaders as Array<PlayerData>).find(
Нужно обрабатывать случаи, когда АПИ возвращает ошибку в ответе, у нас есть для этого хелпер для проверки `hasApiError`, у тебя тип `leaders` в данный момент `PlayerData[] | ApiError`, из-за этого и приходится вот так с типами мучаться. Это касается всех экшенов.
После проверки TS будет знать, что в ответе лежит нужный результат, и вот так явно приводить типы не придётся.

2023-03-29 17:14 UTC, DNLHC commented on packages/client/src/api/leaderboard.ts
> +    return this.http.post<void | APIError>('', {
Странно выглядит пустая строка в пути, можно указать `'/'`, чтобы было понятно, что это корень эндпоинта.

2023-03-29 17:14 UTC, DNLHC commented on packages/client/src/components/game-view/game-view-completed.tsx
> +            });
Здесь `async await` точно нужен? Не вижу здесь необходимости дожидаться ответа, можно просто отправить запрос.

2023-03-29 17:14 UTC, DNLHC commented on packages/client/src/services/leaderboard-slice.ts
> +  filteredPlayers: Array<FilteredUser>;
Можно `PlayerData[]`, `FilteredUser[]`

2023-03-30 20:47 UTC, DNLHC commented on packages/client/src/actions/leaderboard.ts
> +    });
Название переменной `leaders` вводит в заблуждение, мы еще не знаем, вернулся нам список лидеров или ошибка.

2023-03-30 20:47 UTC, DNLHC commented on packages/client/src/actions/leaderboard.ts
> +    }
Здесь лучше выкинуть исключение с переданным сообщением и обрабатывать ошибку в одном месте, у тебя уже ниже стоит `catch`
`throw new Error(leaders.reason)`

2023-03-30 20:47 UTC, DNLHC commented on packages/client/src/api/leaderboard.ts
> +const TEAM_NAME = 'test_colors';
Если значение может меняться от среды, то лучше это вынести в переменную окружения

2023-03-30 20:47 UTC, DNLHC commented on packages/client/src/actions/leaderboard.ts
> +    }
У тебя здесь синхронная функция, а значит ошибка HTTP запроса не отловится в `catch`.
Почему при успешном/неуспешном выполнении в `finally` сбрасывается стейт, так задумано?

2023-03-31 04:55 UTC, alex-kurkov approved these changes

2023-03-31 06:49 UTC, Aleksa-esme commented on packages/client/src/actions/leaderboard.ts
> +    }
Да, для правильного обновления лидерборда - если мы сначала заходим на лидерборд, затем в игру и затем снова на лидерборд. Иначе если до этого игрок не попадал в первую десятку, а после игры попал, то некорректно отображались эти списки

2023-04-01 00:41 UTC, DNLHC approved these changes
Всё круто.
Стоит добавить новую `VITE_TEAM_NAME` переменную, в `.env.sample` и `vite-env.d.ts`

2023-04-02 14:38 UTC, EzhikTT commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +                      active={leader.id === user?.id}
Лучше сначала проверять существование `user` и поле `id` у него, а потом сравнивать уже значение

2023-04-02 14:39 UTC, EzhikTT requested changes

2023-04-02 14:39 UTC, EzhikTT commented on packages/client/src/components/game-view/game-view.tsx
> +      dispatch(getPlayer(user?.id as number));
А здесь не должно быть какого-нибудь дефолтного значения?

2023-04-02 14:39 UTC, EzhikTT commented on packages/client/src/actions/leaderboard.ts
> +        break;
Выходить из цикла брейками - очень плохая практика. Если не хотите доходить до конца, особенно в обычном `for`е, то просто добавьте логическое условие во второй блок цикла

2023-04-03 15:48 UTC, Aleksa-esme commented on packages/client/src/actions/leaderboard.ts
> +        break;
Почему лучше не использовать break?
Не очень поняла какое условие добавить. Переписала по другому функцию, без использования break

2023-04-08 05:57 UTC, merged