SSR prod и dev режимы
Fancy-Colors/FCG-Fancy-Colors-Game pull request #59
Opened 2023-04-04 18:43 UTC by DNLHC

2023-04-06 13:31 UTC, EzhikTT requested changes

2023-04-06 13:31 UTC, EzhikTT commented on packages/server/index.ts
> +        template = await vite!.transformIndexHtml(url, template);
Мб проще проверять существование `vite`?

2023-04-06 13:31 UTC, EzhikTT commented on packages/server/index.ts
> +    app.use(vite!.middlewares);
Зачем тут восклицательный знак? По идее это важная ошибка и ее бы обрабатывать

2023-04-06 13:31 UTC, EzhikTT commented on packages/server/index.ts
> +import { createRequire } from 'node:module';
Зачем этот метод в таком виде и отдельно?

2023-04-06 13:31 UTC, EzhikTT commented on packages/server/index.ts
> +import fs from 'node:fs';
Зачем указывать явно, что это `node`?

2023-04-06 13:31 UTC, EzhikTT commented on packages/client/src/entry-client.tsx
> +  document.querySelector('#root') as HTMLElement,
Почему не используете метод получения по id? `querySelector ` - не рациональный выбор

2023-04-06 13:31 UTC, EzhikTT commented on packages/client/src/components/hooks/use-fullscreen.ts
> +    ? Boolean(
Зачем тут конструктор логической переменной?

2023-04-06 13:31 UTC, EzhikTT commented on packages/client/src/components/client-only/client-only.tsx
> +  return createElement(Fragment, {}, children);
Почему тут вызывается метод создания элемента, а не синтаксис `jsx`?

2023-04-06 13:31 UTC, EzhikTT commented on packages/client/src/components/client-only/client-only.tsx
> +  if (!hasMounted) return null;
А этот код разве не отрабатывает раньше, чем `useEffect`? Это метод работает корректно весь?

2023-04-06 14:17 UTC, DNLHC commented on packages/client/src/components/client-only/client-only.tsx
> +  if (!hasMounted) return null;
Отрабатывает раньше, в этом и задумка. Это обёртка для компонентов, которые не должны рендериться на сервере.

2023-04-06 14:19 UTC, DNLHC commented on packages/server/index.ts
> +import fs from 'node:fs';
- сразу видно, что импортируется встроенный модуль nodejs
- предотвратит случаи, если зависимость в node_modules переопределит встроенный модуль
- в nodejs документации везде используется запись импортов с протоколом node

2023-04-06 14:19 UTC, DNLHC commented on packages/client/src/entry-client.tsx
> +  document.querySelector('#root') as HTMLElement,
уже отвечал https://github.com/Fancy-Colors/FCG-Fancy-Colors-Game/pull/22#discussion_r1123233989

2023-04-06 14:22 UTC, DNLHC commented on packages/client/src/components/hooks/use-fullscreen.ts
> +    ? Boolean(
Потому что тип результата функции - `boolean`, а без приведения типа результат будет `Function` | `undefined` | `boolean`

2023-04-06 14:27 UTC, DNLHC commented on packages/server/index.ts
> +import { createRequire } from 'node:module';
для замены метода `require.resolve` 
В проекте используется ESM система модулей, [где встроенного модуля `require` больше нет](https://nodejs.org/api/esm.html#no-requireresolve)

2023-04-06 14:38 UTC, DNLHC commented on packages/server/index.ts
> +    app.use(vite!.middlewares);
Здесь нет ошибки. В режиме `isDev` у нас `vite` гарантированно есть, но TS об этом не знает, восклицательным знаком мы ему говорим напрямую, что здесь есть значение.

2023-04-06 14:39 UTC, DNLHC commented on packages/server/index.ts
> +        template = await vite!.transformIndexHtml(url, template);
В режиме `isDev` есть vite всегда, проверка в данном случае избыточна.

2023-04-06 14:40 UTC, DNLHC commented on packages/client/src/components/client-only/client-only.tsx
> +  return createElement(Fragment, {}, children);
Не вижу разницы, чем функция смущает? Компонент ничего не рендерит кроме `children`

2023-04-09 14:41 UTC, EzhikTT commented on packages/client/src/components/hooks/use-fullscreen.ts
> +    ? Boolean(
Оки

2023-04-09 14:47 UTC, EzhikTT commented on packages/server/index.ts
> +import fs from 'node:fs';
- Увидел изменения в документации, раньше этого не было 
- если ты используешь методы, которые схожи с названием встроенных в ноду, то, скорее всего, ты делаешь что-то не правильно

2023-04-09 14:47 UTC, EzhikTT commented on packages/server/index.ts
> +import { createRequire } from 'node:module';
Оки

2023-04-09 14:51 UTC, EzhikTT requested changes

2023-04-09 14:51 UTC, EzhikTT commented on packages/server/index.ts
> +    app.use(vite!.middlewares);
Я имел в виде, что важная ошибка, если его нет, и ее бы не игнорировать) 
После инициализаци можно подмешать существование `vite` в значение `isDev` и избавиться здесь и дальше от игнорирование через восклицательный знак

2023-04-09 14:51 UTC, EzhikTT commented on packages/client/src/entry-client.tsx
> +  document.querySelector('#root') as HTMLElement,
В данном случае этот ответ не работает, тк ты получаешь элемент просто по `id`

2023-04-09 14:51 UTC, EzhikTT commented on packages/client/src/components/client-only/client-only.tsx
> +  if (!hasMounted) return null;
И как он узнает, что он не на сервере, если у него всегда `hasMounted === false`? На клиенте он так же получит `false`, я не вижу никаких других зависимостей в компоненте, чтобы дойти до рендера компонентов

2023-04-09 18:33 UTC, DNLHC commented on packages/client/src/components/client-only/client-only.tsx
> +  if (!hasMounted) return null;
На клиенте сработает useEffect хук после первого монтирования, `hasMounted` станет `true` (7 строчка), компонент обновится и отрендерит `children`.
На сервере компонент не смонтируется и вернёт `null`.

2023-04-09 18:41 UTC, DNLHC commented on packages/server/index.ts
> +    app.use(vite!.middlewares);
> Я имел в виде, что важная ошибка, если его нет, и ее бы не игнорировать)

Я выше писал, что `vite` не может не быть вне `isDev`, т.к он в этом контексте и создаётся. Поэтому проверка внутри isDev избыточна.

> После инициализаци можно подмешать существование

Приведёшь пример кода как это сделать?

2023-04-10 05:14 UTC, Aleksa-esme approved these changes

2023-04-11 15:03 UTC, EzhikTT commented on packages/client/src/components/client-only/client-only.tsx
> +  if (!hasMounted) return null;
оки

2023-04-11 15:05 UTC, EzhikTT commented on packages/server/index.ts
> +    app.use(vite!.middlewares);
1) Делаешь `isDev` `let` а не `const` (правда, по логике дальше создать бы другую переменную, что будет логичней)
2) Когда инициализируешь `vite`, подмешиваешь ее в переменную выше `isDev &&= !!vite`
3) Дальше делаешь проверки на эту новую переменную
4) Если `vite` не проиницилизировался, но он он нужен в дев среде, то нужно отлавливать ошибку. Вероятность мала, но она может быть

2023-04-11 15:06 UTC, EzhikTT approved these changes
Все ок, комменты не значительны для принятия

2023-04-11 21:31 UTC, merged