Компонент Toast для уведомлений
Fancy-Colors/FCG-Fancy-Colors-Game pull request #60
Opened 2023-04-05 10:46 UTC by Aleksa-esme

![2023-04-04_15-42-43](https://user-images.githubusercontent.com/58600329/230058724-6027cb61-62a0-4b43-b8f2-8bcb010009dd.png)

2023-04-06 13:40 UTC, EzhikTT requested changes

2023-04-06 13:40 UTC, EzhikTT commented on packages/client/src/components/toast/toast.tsx
> +const notificationRoot = document.querySelector('#notifications') as Element;
Почему не использовать нормальный и оптимальный метод `getElementById`?)
Почему тип не `HTMLElement`?

2023-04-06 19:14 UTC, DNLHC commented on packages/client/src/components/icon/icon.tsx
> +      return <ToastWarning className={styles[size]} fill={color} />;
Иконки вполне могут использоваться и в других местах, можно назвать без привязки к компоненту toast

2023-04-06 19:14 UTC, DNLHC commented on packages/client/src/components/hooks/use-auth.tsx
>        }
Не проще здесь обрабатывать ошибки в одном месте в catch? `response.reason` уже передаёт сообщение с причиной ошибки

2023-04-09 14:54 UTC, EzhikTT approved these changes
Все ок

2023-04-11 08:50 UTC, DNLHC approved these changes

2023-04-23 02:16 UTC, alex-kurkov approved these changes

2023-04-23 06:06 UTC, merged