Feat/game data api/123
Fancy-Colors/FCG-Fancy-Colors-Game pull request #62
Opened 2023-04-07 14:10 UTC by alex-kurkov

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-09 16:13 UTC, EzhikTT requested changes

2023-04-09 16:13 UTC, EzhikTT commented on packages/client/src/app.tsx
> +          loader={async () => {
Лучше вынести это в отдельный метод в тело компонента, и вызывать уже его

2023-04-11 09:29 UTC, DNLHC commented on packages/client/src/pages/game/game.tsx
> +        }
У нас же есть функция `hasApiError`, с ней не придётся ниже приводить тип ответа `as RawGameData`
Разве в `reason` не лежит сообщение об ошибке? Почему не выкидывать его?

2023-04-11 09:29 UTC, DNLHC commented on packages/client/src/pages/game/game.tsx
> +      });
Плохая практика возвращать ошибки, куда она возвращается? Я так понимаю это временно?

2023-04-11 09:29 UTC, DNLHC commented on packages/client/src/pages/game/game.tsx
> +        }
В каких случаях у нас может измениться `id` игры на этой странице?

2023-04-25 04:18 UTC, Aleksa-esme approved these changes

2023-04-27 12:21 UTC, merged