forum-api-threads
Fancy-Colors/FCG-Fancy-Colors-Game pull request #68
Opened 2023-05-02 17:06 UTC by mozg3000

### Какую задачу решаем
Реализует получение тредов из апи.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-04 17:48 UTC, DNLHC reviewed
Нужно поправить/удалить `mock/forum-threads.ts` в соответствии с новым форматом ответа сервера. Сейчас TS ругается.

2023-05-04 17:48 UTC, DNLHC commented on packages/client/src/api/forum.ts
> +  }
У нас эта логика уже есть в BaseApi классе, почему не сделать extend?

2023-05-04 17:48 UTC, DNLHC commented on packages/client/src/api/forum.ts
> +export const forumApi = new ForumApi('');
Вместо пустой строки можно передать базовый путь эндпоинта, не придётся во всех ручках добавлять `/threads` в пути запроса

2023-05-05 10:54 UTC, mozg3000 commented on packages/client/src/api/forum.ts
> +  }
Там зашит baseUrl ведущий на яндекс практикум. У форума же другой базовый адрес. Поэтому тут очень странное наследования получается.

2023-05-05 11:02 UTC, mozg3000 commented on packages/client/src/api/forum.ts
> +export const forumApi = new ForumApi('');
насколько я понял роут /messages тогда не возможно будет использовать в методе getThread.

2023-05-05 11:20 UTC, mozg3000 commented
> Нужно поправить/удалить `mock/forum-threads.ts` в соответствии с новым форматом ответа сервера. Сейчас TS ругается.

поправил мок чтоб не ругался.

2023-05-05 19:00 UTC, DNLHC commented on packages/client/src/api/forum.ts
> +  }
Значит нужно адаптировать BaseApi для работы с локальным апи и яндекс апи.
Переменную `VITE_API_BASE_URL` сделать `http://localhost:5000/api`, а для яндекс апи просто добавлять `/v2` в url.
`VITE_LOCAL_API_BASE_URL` удалить

2023-05-05 19:01 UTC, DNLHC commented on packages/client/src/api/forum.ts
> +export const forumApi = new ForumApi('');
А сделать для `/messages` отдельный класс MessagesApi?

2023-05-11 05:51 UTC, EzhikTT requested changes

2023-05-11 05:51 UTC, EzhikTT commented on packages/client/src/api/forum.ts
> +  }
А почему нельзя при наследовании переопределить свойство?

2023-05-17 11:56 UTC, DNLHC commented
@mozg3000 Игорь, подтяни обновления из main, там переделан BaseApi класс, теперь в конструктор можно передать нужный HTTPClient, в твоём случае можно сделать так:
```ts
import { localHttpClient } from './api-clients';

export class ForumApi extends BaseApi {
  //...
}

export const forumApi = new ForumApi(localHttpClient('/threads'));
```
Дублирование кода нужно убрать, посмотри примеры в других апи.

2023-05-18 00:44 UTC, merged