Переключение цветовых тем на сервере, auth middlewares
Fancy-Colors/FCG-Fancy-Colors-Game pull request #69
Opened 2023-05-06 05:50 UTC by DNLHC

### Какую задачу решаем
Перенёс переключение цветовой темы на сервер в соответствии с ТЗ
Если пользователь авторизован, то при переключении, текущая тема сохранится в БД
Для неавторизованных пользователей текущая тема сохраняется в кукисах.

Добавил middlewares авторизации
authContext - получает текущего пользователя и сохраняет в контекст области запроса через [express-http-context](https://www.npmjs.com/package/express-http-context), чтобы другие middlewares и роуты имели доступ к пользователю
authGuard - запрещает доступ неавторизованным пользователям к роуту

2023-05-11 05:52 UTC, alex-kurkov approved these changes

2023-05-14 08:42 UTC, Aleksa-esme approved these changes

2023-05-16 05:23 UTC, EzhikTT commented on packages/client/src/api/auth.ts
> +    super('/v2/auth');
А почему бы это не вынести в свойство и переопределять его?

2023-05-16 05:25 UTC, EzhikTT requested changes

2023-05-16 05:25 UTC, EzhikTT commented on packages/server/src/index.ts
> +  app.use(cookieParser());
А куки не надо выше написать? Они не нужны для `httpContext.middleware`?

2023-05-16 07:05 UTC, DNLHC commented on packages/server/src/index.ts
> +  app.use(cookieParser());
Нет, не нужны

2023-05-16 19:03 UTC, merged