Lib/error stub/90
Fancy-Colors/FCG-Fancy-Colors-Game pull request #7
Opened 2023-02-24 13:42 UTC by mozg3000

* Использовались стили из ветки /lib/global-styles/73
### Компонент заглушка для ошибки
Выводит сообщение об ошибке

##### Применение

```tsx
<ErrorStub
  title={'404'}
  subTitle={'Упс... Мы не можем найти страницу которую вы искали :('}
>
  <button>Перейти на главную</button>
</ErrorStub>
```

##### Описание

Элементы инлайновые, выравнивание происходит через

```css
 {
  text-align: center;
}
```

Кнопка передаётся как дитё.

##### Представление

![img](https://user-images.githubusercontent.com/45194783/221191555-d68214e5-0d3e-40b9-ae6e-4b2bc365c241.png)

2023-02-24 16:55 UTC, alex-kurkov requested changes
нельзя наследоваться от ветки, отличной от ui-kit, так как в PR попадут не только файлы, относящиеся к issue, но и файлы совершенно другого issue, а это потенциальные конфликты при мердже

2023-02-24 16:55 UTC, alex-kurkov commented on packages/client/src/components/error-stub/error-stub.module.pcss
> +  color: var(--color-accent-primary);
Здесь можно поставить фолбек на цвет (тем более пока нет глобальных переменных)
```
background-color: var(--color-light-primary, #6644ec);
```

2023-02-24 16:55 UTC, alex-kurkov commented on packages/client/src/components/error-stub/error-stub.tsx
> +import React, { FC } from 'react'; // eslint-disable-line @typescript-eslint/no-unused-vars
а для чего // eslint-disable-line @typescript-eslint/no-unused-vars?
React можно не импортировать

2023-02-24 16:55 UTC, alex-kurkov commented on packages/client/src/components/error-stub/error-stub.tsx
> +  children?: JSX.Element | JSX.Element[];
не обязательно указывать children, так как алиас FC уже знает, что может быть такой пропс

2023-02-24 16:55 UTC, alex-kurkov commented on packages/client/src/components/error-stub/Readme.md
> +  subTitle={'Упс... Мы не можем найти страницу которую вы искали :('}
и тут:
```
subTitle="Упс... Мы не можем найти страницу которую вы искали :("
```

2023-02-24 16:55 UTC, alex-kurkov commented on packages/client/src/components/error-stub/Readme.md
> +  title={'404'}
тут можно без скобок:
```
title="404"
```

2023-02-24 16:55 UTC, alex-kurkov commented on packages/client/src/components/error-stub/index.ts
> +import { ErrorStub } from './error-stub';
можно в одну строку 
```
export { ErrorStub } from './error-stub';
```

2023-02-24 17:04 UTC, mozg3000 commented on packages/client/src/components/error-stub/error-stub.tsx
> +import React, { FC } from 'react'; // eslint-disable-line @typescript-eslint/no-unused-vars
Раньше вроде нужно было.

2023-02-24 17:06 UTC, mozg3000 commented on packages/client/src/components/error-stub/error-stub.tsx
> +  children?: JSX.Element | JSX.Element[];
IDE с этим не согласно, поэтому добавил.
![image](https://user-images.githubusercontent.com/45194783/221242409-3c9d6d79-d21c-4a8d-8564-8c176b1136ca.png)

2023-02-24 17:09 UTC, mozg3000 commented on packages/client/src/components/error-stub/error-stub.tsx
> +  children?: JSX.Element | JSX.Element[];
и линтер тоже не согласен
![image](https://user-images.githubusercontent.com/45194783/221242965-ba61c3c9-2c9d-4b67-8639-2adadee02f13.png)

2023-02-24 18:30 UTC, DNLHC approved these changes

2023-02-24 18:30 UTC, DNLHC commented on packages/client/src/components/error-stub/error-stub.tsx
> +const ErrorStub: FC<ErrorStubProps> = (props) => {
```suggestion
const ErrorStub: FC<ErrorStubProps> = ({ title, message, children }) => {
```
можно деструктуризацию сразу в аргументе сделать

2023-02-25 06:23 UTC, alex-kurkov approved these changes

2023-02-25 06:24 UTC, merged