nginx сервис
Fancy-Colors/FCG-Fancy-Colors-Game pull request #73
Opened 2023-05-13 07:48 UTC by DNLHC

### Какую задачу решаем

Перенёс раздачу статики с express на nginx
Добавил модуль brotli для сжатия с фоллбэком на gzip для браузеров не поддерживающих br формат.
Из коробки nginx не поддерживает переменные окружения в конфигах, поэтому в docker образе nginx доступен модуль envsubst, который трансформирует шаблон конфига (nginx/templates/*.template) в валидный конфиг с заменой переменных окружения. Подробней [тут](https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119)
`Dockerfile.nginx` создан [следуя документации](https://github.com/nginxinc/docker-nginx/tree/master/modules#adding-third-party-modules-to-nginx-official-image) способа расширения nginx сторонними модулями (brotli)

2023-05-14 08:37 UTC, Aleksa-esme approved these changes

2023-05-16 05:32 UTC, EzhikTT requested changes

2023-05-16 05:32 UTC, EzhikTT commented on nginx/nginx.conf
> +user nginx;
Зачем дефолтный конфиг под гит добавлять?

2023-05-16 05:32 UTC, EzhikTT commented on Dockerfile.nginx
> +FROM nginx:mainline as builder
А зачем так сложно? Почему в композе не взять готовый образ и все?

2023-05-16 07:01 UTC, DNLHC commented on nginx/nginx.conf
> +user nginx;
Этот конфиг используется в докере.

2023-05-16 07:03 UTC, DNLHC commented on Dockerfile.nginx
> +FROM nginx:mainline as builder
В описании в последнем пункте отметил [почему](https://github.com/nginxinc/docker-nginx/tree/master/modules#docker-compose-with-pre-packaged-modules)

2023-05-16 07:50 UTC, merged